### ISSUE TITLE
Registry entry on Windows is removed after one boot

### ISSUE THREAD

**Issue by joshsharp** [zzzgydi/auto-launch#11]
Hi, this is a duplicate of an issue I made on a downstream package here: https://github.com/tauri-apps/plugins-workspace/issues/771

I'm sorry but this is going to be a very vague bug report as I'm having trouble understanding what's happening.

Essentially what's happening is that upon calling `enable()` in Tauri, which wraps the `enable` method in `auto-launch`, the registry entry is added on Windows successfully in the correct location and upon next boot the app is successfully launched at startup. However, somehow (upon launch of my app?) the Windows registry item in the `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` location is somehow removed. If `enable()` isn't called again, the app will fail to run on next boot.

The Tauri wrapper is very simple so I am hoping that, as I haven't heard from them, the problem may be something that relates to your crate too, so you can tell me where I'm going wrong.

My only suspicion is that this is [something to do with](https://learn.microsoft.com/en-gb/windows/win32/api/winreg/nf-winreg-regcreatekeyexa) `REG_OPTION_VOLATILE` however I don't see why entries would be made this way, as non-volatile is the default.

Is there anything you can think of that I am missing?

Thanks for your help.

**Comment by zzzgydi** [comment]
I briefly reviewed my code and didn't see any bugs that could cause this issue. You can pay attention to whether you have recently installed any other software or services that may modify the registry. Alternatively, check the system logs to see which process modified the registry at what time.

**Comment by joshsharp** [comment]
Thanks for looking into this! It's happening for some of my users, not just me, so it shouldn't be related any other software. I guess I will look for system logs.
