### ISSUE TITLE
Please fix tests and push new vesion to crates.io

### ISSUE THREAD

**Issue by Levminer** [zzzgydi/auto-launch#3]
Hi!

I'm using your crate in my app, but can't compile on macOS because the tests on the main branch are failing, and I'm pulling the latest changes because of the costume args.

Please fix the tests and publish the new version. I tired to fix the test myselft but I didn't succeed.

Thanks.

**Comment by zzzgydi** [comment]
Hi, I have fixed the tests.

**Comment by Levminer** [comment]
Thank you!
