### ISSUE TITLE
Windows - Does not report that programs disabled in Task Manager > Startup are disabled

### ISSUE THREAD

**Issue by OmegaJak** [zzzgydi/auto-launch#7]
After enabling startup using auto-launch, the program will appear inside the Task Manager "Startup" tab. If it is then disabled, auto-launch still reports the program as being enabled.

Setting this values changes the registry entry inside `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run` for the app. When enabled, the hex value is 0x020000000000000000000000 ([source](https://community.spiceworks.com/topic/2346007-windows-10-task-manager-startup-disabled-items-registry-location), also verified myself on Windows 10). When disabled, it appears to be something else, it's not consistent between apps.

It would be nice if `AutoLaunch::is_enabled()` factored this registry value into its result to reflect changes made in Task Manager. I intend to implement this and raise a PR for it soon.

**Comment by OmegaJak** [comment]
Note that the hex value when enabled isn't always 0x02..., I saw 0x00 and others have reported 0x06 and 0x08. A better test seems to be whether the last 8 bytes are zeros. More details in the PR.

**Comment by zzzgydi** [comment]
I have fixed some issues and updated to version 0.5.0, you can give it a try

**Comment by OmegaJak** [comment]
Updated to use 0.5.0, everything seems good, thanks!
